name: jsonx
version: 1.2.0
author: Man Hoang <jolleekin@outlook.com>
description: An extended JSON library that supports the encoding and decoding of arbitrary objects.
homepage: https://github.com/jolleekin/jsonx
